# Generated by Django 5.0.7 on 2024-07-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField()),
                ('current_load', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100)),
                ('sku_desc', models.CharField(max_length=255)),
                ('sut', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_order_number', models.IntegerField()),
                ('date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
                ('process_order_qty', models.IntegerField()),
                ('bin_number', models.CharField(blank=True, max_length=100)),
                ('pallet_qty', models.IntegerField()),
                ('transfer_order_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('sku_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.materialmaster')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionline')),
            ],
        ),
    ]
