# Generated by Django 5.0.7 on 2024-07-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='bin_number',
        ),
        migrations.AddField(
            model_name='pallet',
            name='capacity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bin',
            name='capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bin',
            name='current_load',
            field=models.FloatField(),
        ),
    ]
